### ISSUE TITLE
media service first milestone

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#1]
### Story
as a user/client I want the ability to add and get a media file. 

### Tickets
- [x] Create open-API definition 
- [x] Add sequence & ERD diagrams
- [x] Update CI/CD
- [ ] Update deployment & docker config files
- [x] Create add media endpoint
- [x] Create get media endpoint 

### Acceptance criteria
- After being able to send a media file, store it locally in file system, send its url + entity_id + entity_type to rabbitMQ broker, then get it.
