### ISSUE TITLE
Make data/hard-coded values as a config

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-media#13]
### Story
- [ ] We should remove any hard-coded data and make them all to the config and use env vars to switch between them, example:
the queue name to be used for the rabbitMQ.

### Prerequisites
- [ ] None

### Tasks
- [ ] Remove any hard-coded value and add them to the config

### Acceptance criteria
- [ ] Any value that is hard-coded must be removed and replaced with its corresponding value (env var) from the confing.
