### ISSUE TITLE
update openAPI

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#21]
### Story
- The current openAPI definitions are not updated. Update media creation request body properties to be required. Also the response to be required 

### Tasks
- [ ] update `file`, `entity_type`, entity_id` properties to be required
- [ ] update `ack` to be required

### Acceptance criteria
- [ ] whenever the swaggerUI render correctly after updating the openAPI.
