### ISSUE TITLE
Use Deployed DB

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#24]
### Story
- [ ] Currently we use elephantSQL DB. We should migrate to the deployed DB in kubernetes cluster

### Tasks
- [ ] add database.yaml deployment
- [ ] pass db environment variables to deploy.yaml along with credentials values from kubernetes `secrets`
- [ ] change database connection options to be able to use the db env variables
- [ ] add the required db env variables in github workflows files

### Acceptance criteria
- [ ] whenever the application runs smoothly with the deployed DB
