### ISSUE TITLE
Add sequence & ERD diagrams

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#3]
### Story
as a user/client I want the ability to have the sequence diagrams of the media service

### Prerequisites
- [ ] open-api definitions

### Tasks
- [ ] add sequence diagrams
- [ ] add ERD diagrams 

### Acceptance criteria
- sequence diagrams fulfill the open-api definition and satisfy all endpoints
