### ISSUE TITLE
Update CI/CD

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#4]
### Story
as a user/client I want the ability to have continues integration & continues deployment implemented

### Prerequisites
- [ ] dockerfile
- [ ] kubernetes deployment files (service, ingress, deployment, namespace)

### Tasks
- [ ] change the needed environment variables to work in media service 
- [ ] add a working kubernetes cluster secret

### Acceptance criteria
- Whenever a pr is opened, it gets deployed. Also the development branch gets deployed each time PR is merged.
