### ISSUE TITLE
add media endpoint

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-media#5]
### Story
as a user/client I want the ability to add a media file. 

### Prerequisites
- [x] CI/CD
- [x] open-api definition
- [x] sequence & ERD diagrams 

### Tasks
- [ ] add global validation pipe
- [ ] add media entity 
- [ ] add media repository
- [ ] add multer configuration ( store files in disk + accept only **png**, **jpeg** and **jpg** + max file size **10 MB**
- [ ] add DTO for request body 
- [ ] add interface for the response
- [ ] add media module, media controller & media servide
- [ ] add unit tests for media controller & media service
- [ ] update migration file 
- [ ] remove example module 
- [ ] send the url of the added media file + entity_type + entity_id to rabbitMQ broker

### Acceptance criteria
- After being able to send a media file, store it locally in file system send its url + entity_type + entity_id to rabbitMQ broker, then respond with acknowledgment
